# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keepac < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/NiclasvanEyk/keepac/releases/download/0.0.3/keepac_Darwin_arm64.tar.gz"
      sha256 "c5da86b4b4bf6eb626c11af48309262bab74daeb2cedbdac6d7a253fd9168755"

      def install
        bin.install "changelog"
        bash_completion.install "completions/changelog.bash" => "changelog"
        zsh_completion.install "completions/changelog.zsh" => "_changelog"
        fish_completion.install "completions/changelog.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/NiclasvanEyk/keepac/releases/download/0.0.3/keepac_Darwin_x86_64.tar.gz"
      sha256 "02349e0f3774bd1fd2e8d456bf83f2054a5cfcaca1575d934e2d13c3ecbb4de0"

      def install
        bin.install "changelog"
        bash_completion.install "completions/changelog.bash" => "changelog"
        zsh_completion.install "completions/changelog.zsh" => "_changelog"
        fish_completion.install "completions/changelog.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NiclasvanEyk/keepac/releases/download/0.0.3/keepac_Linux_arm64.tar.gz"
      sha256 "a07a68475f05f31fda11ee33a0a0cb34d237d25d597ab3b288cf9990a92b0016"

      def install
        bin.install "changelog"
        bash_completion.install "completions/changelog.bash" => "changelog"
        zsh_completion.install "completions/changelog.zsh" => "_changelog"
        fish_completion.install "completions/changelog.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/NiclasvanEyk/keepac/releases/download/0.0.3/keepac_Linux_x86_64.tar.gz"
      sha256 "dc7b3bd1b7f9bfb83846aa6277e145ac78d9f768ca0ffbf7f09c52d035cb3c56"

      def install
        bin.install "changelog"
        bash_completion.install "completions/changelog.bash" => "changelog"
        zsh_completion.install "completions/changelog.zsh" => "_changelog"
        fish_completion.install "completions/changelog.fish"
      end
    end
  end
end
