# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keepac < Formula
  desc ""
  homepage "https://github.com/NiclasvanEyk/keepac"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/NiclasvanEyk/keepac/releases/download/0.1.0/keepac_Darwin_arm64.tar.gz"
      sha256 "97438993ef19c9836485dc8b264f9740f5e5ef31e7268f79b15cfc8edc18162e"

      def install
        bin.install "changelog"
        bash_completion.install "completions/changelog.bash" => "changelog"
        zsh_completion.install "completions/changelog.zsh" => "_changelog"
        fish_completion.install "completions/changelog.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/NiclasvanEyk/keepac/releases/download/0.1.0/keepac_Darwin_x86_64.tar.gz"
      sha256 "4dd60e15549596695eccfbbe3f17737b0b19d7a5f5270b7d1594d30e8a931d2c"

      def install
        bin.install "changelog"
        bash_completion.install "completions/changelog.bash" => "changelog"
        zsh_completion.install "completions/changelog.zsh" => "_changelog"
        fish_completion.install "completions/changelog.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/NiclasvanEyk/keepac/releases/download/0.1.0/keepac_Linux_x86_64.tar.gz"
      sha256 "4feb433d3107f7eaaecb6b2d21754565b50da5ce432bb871aea031ec53663fab"

      def install
        bin.install "changelog"
        bash_completion.install "completions/changelog.bash" => "changelog"
        zsh_completion.install "completions/changelog.zsh" => "_changelog"
        fish_completion.install "completions/changelog.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NiclasvanEyk/keepac/releases/download/0.1.0/keepac_Linux_arm64.tar.gz"
      sha256 "7856e9e4af1a4b76d97a194863b0516fb25b83dd3a009ca77ec4b133fab5ee13"

      def install
        bin.install "changelog"
        bash_completion.install "completions/changelog.bash" => "changelog"
        zsh_completion.install "completions/changelog.zsh" => "_changelog"
        fish_completion.install "completions/changelog.fish"
      end
    end
  end
end
