# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keepac < Formula
  desc ""
  homepage "https://github.com/NiclasvanEyk/keepac"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NiclasvanEyk/keepac/releases/download/0.0.7/keepac_Darwin_x86_64.tar.gz"
      sha256 "e44e32f8f244a9617d19606e58fdb3626f0a97911e6a5f413e6bb9ee25c6b904"

      def install
        bin.install "changelog"
        bash_completion.install "completions/changelog.bash" => "changelog"
        zsh_completion.install "completions/changelog.zsh" => "_changelog"
        fish_completion.install "completions/changelog.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NiclasvanEyk/keepac/releases/download/0.0.7/keepac_Darwin_arm64.tar.gz"
      sha256 "c5b279dca96b2bbbd116ecf7c140c44c57280a831b80de6c80c4fc7d7854cde4"

      def install
        bin.install "changelog"
        bash_completion.install "completions/changelog.bash" => "changelog"
        zsh_completion.install "completions/changelog.zsh" => "_changelog"
        fish_completion.install "completions/changelog.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/NiclasvanEyk/keepac/releases/download/0.0.7/keepac_Linux_x86_64.tar.gz"
      sha256 "1f2e6ffd42c7aca91f483b77ae8cd4a348b25fbd6cff7995e151951d5e0e552a"

      def install
        bin.install "changelog"
        bash_completion.install "completions/changelog.bash" => "changelog"
        zsh_completion.install "completions/changelog.zsh" => "_changelog"
        fish_completion.install "completions/changelog.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NiclasvanEyk/keepac/releases/download/0.0.7/keepac_Linux_arm64.tar.gz"
      sha256 "ea12c578878a1b4fa4a8f33c2c38719725817ae88c86e7e6ba96f6d5d625978e"

      def install
        bin.install "changelog"
        bash_completion.install "completions/changelog.bash" => "changelog"
        zsh_completion.install "completions/changelog.zsh" => "_changelog"
        fish_completion.install "completions/changelog.fish"
      end
    end
  end
end
